### ISSUE TITLE
SharedConstantsError.missingSMPrivilegedExecutables occurs after adding sparkle to project

### ISSUE THREAD

**Issue by chaosong** [trilemma-dev/SwiftAuthorizationSample#12]
After adding [Sparkle](https://sparkle-project.org/documentation/) to project, `SharedConstantsError.missingSMPrivilegedExecutables` occurs when the project starts running. Is there something colliding?
Maybe I should report issue to the sparkle community,  but I think adding sparkle to a project with privileges helper perhaps a common routine.
Any idea to fix the error, thanks!

**Comment by jeff-h** [comment]
Hmm, my app uses these XPC packages and Sparkle and I've not hit this particular issue. Hopefully it's at least some help to you to know there's nothing intrinsically problematic using these packages together.

**Comment by jeff-h** [comment]
This error is only thrown from one place. Have you stepped through that code to see what's failing specifically?

```swift
if let helperToolLabel = (Bundle.main.infoDictionary?["SMPrivilegedExecutables"]
                                          as? [String : Any])?.first?.key {
    self.helperToolLabel = helperToolLabel
    let relativeBundledLocation = "Contents/Library/LaunchServices/\(helperToolLabel)"
    let bundledLocation = URL(fileURLWithPath: relativeBundledLocation,
        relativeTo: Bundle.main.bundleURL).absoluteURL
    self.bundledLocation = bundledLocation
    launchdPropertyList = try HelperToolLaunchdPropertyList(from: bundledLocation)
} else {
    throw SharedConstantsError.missingSMPrivilegedExecutables
}
```

**Comment by jakaplan** [comment]
Closing due to lack of follow up. If this continues to be an issue, please reopen.
