### ISSUE TITLE
Multiple arguments for command

### ISSUE THREAD

**Issue by LSDdev** [trilemma-dev/SwiftAuthorizationSample#5]
First of all, thanks for this really really great resource for something that is far from trivial! 

I've been playing with this and getting to understand how these different pieces work together. I've bumped into issue that I can't figure out which is how do I pass multiple arguments correctly. I tried to expand the 'thermal' command and added a case like below

```Swift
enum ThermalArgs: String, Codable, CaseIterable {
  case levels = "levels"
  case config = "config"
  case simulate = "simulate gpu nominal"
  var requiresAuth: Bool {
      return false
   }
}
```

However not that, or any other command with multiple arguments I've tried works. It errors indicating that the command's arguments are not correct. This same happens every command I've tried when there is more than one arguments to be passed.

**Comment by jakaplan** [comment]
Spaces don't have any relationship to the number of arguments; that's just a convention used by terminals (such as Terminal.app). When you're writing `case simulate = "simulate gpu nominal"` the spaces don't make them into separate arguments.

If you wanted to modify the sample to do this you'd need to change how the `arguments` property is populated, currently the `rawValue` is provided as the only argument: https://github.com/trilemma-dev/SwiftAuthorizationSample/blob/d5759c82e3f9e2e5f47e23c0e9969e7f5a693c39/Shared/AllowedCommand.swift#L81-L91



The argument array is then used when running the process, so this would work without modification:
https://github.com/trilemma-dev/SwiftAuthorizationSample/blob/d5759c82e3f9e2e5f47e23c0e9969e7f5a693c39/SwiftAuthorizationHelperTool/AllowedCommandRunner.swift#L43-L53
