### ISSUE TITLE
Failed to install Helper Tool - Authorization failure

### ISSUE THREAD

**Issue by rluvaton** [trilemma-dev/SwiftAuthorizationSample#6]
When I run the sample from Xcode and click install after entering the password I get an authorization failure

<img width="667" alt="image" src="https://user-images.githubusercontent.com/16746759/156900100-0071e85e-6aa8-442b-99c9-b195927aedc4.png">

The state that calls the `install` function:
https://github.com/trilemma-dev/SwiftAuthorizationSample/blob/4a63947f9ebe7db177763727f40dd5f3d1ff7477/SwiftAuthorizationApp/ViewController.swift#L209-L218

### Env
**Machine:** Macbook Pro M1 Max
**OS:** macOS Monterey 12.2.1
**XCode:** Version 13.2.1 (13C100)
```
$ swift --version
swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: arm64-apple-macosx12.0
```

**Comment by rluvaton** [comment]
The issue was fixed somehow,
What I did that may help:
1. Uncheck the _Based on dependency analysis_ in the _Run Script_ in the _Build Phases_
2. Run the Swift Authorization Helper Tool

**Comment by jakaplan** [comment]
Thanks for the report. Unfortunately I can't see how unchecking that box would make a difference as the documentation for the underlying error you encountered is:
> The request required authorization (i.e. adding a job to the `kSMDomainSystemLaunchd` domain) but the `AuthorizationRef` did not contain the required right.

The required right should be _always_ present, the code path used by the sample unconditionally adds it. 

When you said "Run the Swift Authorization Helper Tool" what do you mean by that?
